repository_type: pipeline

nf_core_version: 3.1.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-magigib_logo_light.png
    - docs/images/nf-core-magigib_logo_light.png
    - docs/images/nf-core-magigib_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - CITATIONS.md
    - assets/multiqc_config.yml
    - nextflow_schema.json
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CITATIONS.md
    - assets/multiqc_config.yml
    - nextflow_schema.json
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-magigib_logo_light.png
    - docs/images/nf-core-magigib_logo_light.png
    - docs/images/nf-core-magigib_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge
  schema_lint: false
  schema_params: false
  schema_description: false
  included_configs: false

template:
  org: sateeshperi
  name: magigib
  description: metagenome assembly
  author: Sateesh Peri
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - ci
    - igenomes
    - github_badges
    - nf_core_configs
    - citations
    - codespaces
    - multiqc
    - fastqc
    - nf_schema
    - email
    - adaptivecard
    - slackreport
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
